name: Build & Test
on:
  push:
    branches: ["v1.5.x/master"]
  pull_request:
    branches: ["v1.5.x/master"]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  linux-windows-build:
    name: Linux & Windows Build
    runs-on: ubuntu-latest
    timeout-minutes: 90
    steps:
      - name: Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.7"

      - name: OS Packages
        run: |
          sudo apt-get update --fix-missing && sudo apt-get -y install \
          git build-essential zlib1g zlib1g-dev wget zip unzip \
          mingw-w64 binutils-mingw-w64 g++-mingw-w64 gcc-multilib

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Go Assets
        run: ./go-assets.sh

      - name: Make
        run: make linux

      - name: Test
        run: ./sliver-server unpack --force && ./go-tests.sh

      - name: Make Windows
        run: make windows

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    timeout-minutes: 90
    steps:
      - name: Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.7"

      - name: Mingw
        run: brew install mingw-w64

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Git Fetch Tags
        run: git fetch --prune --unshallow --tags -f

      - name: Go Assets
        run: ./go-assets.sh

      - name: Make
        run: make macos

      - name: Test
        env:
          SLIVER_CC_32: /usr/local/bin/i686-w64-mingw32-gcc
          SLIVER_CC_64: /usr/local/bin/x86_64-w64-mingw32-gcc
        run: ./sliver-server unpack --force && ./go-tests.sh
